### ISSUE TITLE
Attendance not saved

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#101]
[screen-capture.webm](https://github.com/antonym8/Tentacle/assets/142376069/9a2b2986-cb8a-4aa9-8b03-067776e8ed2e)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed 09-04-2024

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Attendance not saved - Not fixed

[Video 6-12 at 5.30.webm](https://github.com/antonym8/Tentacle/assets/167422482/66170153-5f47-46f3-a19b-2a3713900bc7)

**Comment by Gokilavani-m8** [comment]
Attendance not saved - Not fixed

[Video 6-12 at 5.37.webm](https://github.com/antonym8/Tentacle/assets/167422482/dc069a9d-87e6-4c53-86b2-af90d0b78f25)

**Comment by M8Balaji** [comment]
@yogiofficemail https://github.com/antonym8/Tentacle/issues/101 - Check this issue

**Comment by M8Balaji** [comment]
https://tssapidemo.m8itsolutions.in/api/AddEmployeeAttendance

**Comment by yogiofficemail** [comment]
frontend side the month and year is wrongly passed to the api it is always passing the current month and year

**Comment by M8Balaji** [comment]
Fixed, But not working 
![image](https://github.com/antonym8/Tentacle/assets/150112780/847df843-744d-4c1f-8211-0a149a2b2c9b)
![image](https://github.com/antonym8/Tentacle/assets/150112780/847df843-744d-4c1f-8211-0a149a2b2c9b)
![image](https://github.com/antonym8/Tentacle/assets/150112780/847df843-744d-4c1f-8211-0a149a2b2c9b)

@yogiofficemail

**Comment by yogiofficemail** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
Pass
