### ISSUE TITLE
Client / Allowance -> When edit and change designation, new allowance created

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#107]
[screen-capture (3).webm](https://github.com/antonym8/Tentacle/assets/142376069/53bc9112-a5b6-4964-9e2c-01963584f77b)

**Comment by M8Balaji** [comment]
@yogiofficemail 
https://tssapidemo.m8itsolutions.in/api/clientallowancedeductionsList/37

**Comment by yogiofficemail** [comment]
[05.07.2024 21_08.webm](https://github.com/antonym8/Tentacle/assets/112150339/5c0dd702-9281-4e12-b92e-5f77f6cb6b44)
fixed

**Comment by Gokilavani-m8** [comment]
While changing the designation, it shouldn't create new allowance. Need to change it.

**Comment by yogiofficemail** [comment]
send the old designation id as   old_category_id then it will fix @M8Balaji 


![image](https://github.com/antonym8/Tentacle/assets/112150339/19301995-5a4c-4855-9d0f-f81e79f1b4c3)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Not fixed

[Recording-20240712_054634.webm](https://github.com/user-attachments/assets/67e44f46-43fe-44bb-b5ca-0f58b5214266)

**Comment by Gokilavani-m8** [comment]
Deductions - After changing the percentage and clicking on the save icon, the previous percentage added automatically. Only the new percentage should be shown not the previous percentage. Allowance also added automatically. It shouldn't added like that. Need to change it. 
Delete icon - After deleting in allowance & deduction and clicking on the save icon, the previous allowance and deduction has been added in the page. Delete icon not working

[Recording-20240712_060544.webm](https://github.com/user-attachments/assets/682462e8-095c-463e-b308-a8fb202418ba)

**Comment by Gokilavani-m8** [comment]
Pass
