### ISSUE TITLE
Holiday Scheme>Add New>Calculating Working Days

### ISSUE THREAD

**Issue by Nounitha-m8** [antonym8/Tentacle#128]
Calculating Working days - Does not Show negative values.

![Screenshot (288)](https://github.com/antonym8/Tentacle/assets/167423207/128e61ae-3d0c-4ef9-8009-f81aeca64f1d)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Not Fixed

![Screenshot (331)](https://github.com/antonym8/Tentacle/assets/167422482/3cbd8857-3060-473f-984d-dcdba5554166)

**Comment by Gokilavani-m8** [comment]
Pass
