### ISSUE TITLE
Fine>List page

### ISSUE THREAD

**Issue by Nounitha-m8** [antonym8/Tentacle#129]
While clicking on three dot icon there is only edit option is shown, need to include Delete & Show option.

![Screenshot (287)](https://github.com/antonym8/Tentacle/assets/167423207/8b18c174-c46c-4082-90b6-61592bf5db56)

**Comment by M8Balaji** [comment]
Delete option added and Show option Not needed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Not fixed

![Screenshot (332)](https://github.com/antonym8/Tentacle/assets/167422482/421dda14-afaa-45d0-b6b2-563602c77ffb)

**Comment by Gokilavani-m8** [comment]
Pass
