### ISSUE TITLE
Employement Type>Add New>Add employment type

### ISSUE THREAD

**Issue by Nounitha-m8** [antonym8/Tentacle#130]
1.Rename the field name as Staff name not as staffing name - Need to correct it.
2.Need to change the placeholder as Enter staff name.

![Screenshot (283)](https://github.com/antonym8/Tentacle/assets/167423207/e3b9dd7f-9eb6-4165-982e-298beb0cd7a5)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Not fixed

![Screenshot (333)](https://github.com/antonym8/Tentacle/assets/167422482/eb130b3f-94c9-4e7f-a386-fed6dd68f7b9)

**Comment by Gokilavani-m8** [comment]
1.Rename the field name as **Staff name** not as staffing name - Need to correct it.
2. Rename the alert message as **Please enter "Staff name"**

![Screenshot (344)](https://github.com/antonym8/Tentacle/assets/167422482/ce6a48f0-101f-481e-956e-5987439381fd)

**Comment by yogiofficemail** [comment]
fronend bug

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Pass
