### ISSUE TITLE
Break -> Save button disabled in edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#23]
[screen-capture (7).webm](https://github.com/antonym8/Tentacle/assets/142376069/aba2f2ee-d386-4387-9e95-e91bb92addcf)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 03-04-2024

**Comment by Nounitha-m8** [comment]
Not Fixed
Break Name> Proper validation message should display

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Pass
