### ISSUE TITLE
Branch -> Not able to add new branch

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#42]
Added successfully message displayed but new branch not  added in list page

[screen-capture (15).webm](https://github.com/antonym8/Tentacle/assets/142376069/c57fddc0-137d-4702-8567-a73c30ba122f)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-04-2024(As per client changes, changed the UI branch as company)

**Comment by M8Balaji** [comment]
@yogiofficemail  https://tssapidemo.m8itsolutions.in/api/addBranch
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'company_register_no' in 'field list' (SQL: insert into `branch` (`name`, `address`, `phone`, `town`, `state`, `pincode`, `gst_no`, `company_register_no`, `logo`, `branch_image`, `contact_person`, `contact_email`, `no_of_floors`, `is_active`, `updated_at`, `created_at`) values (balaji's comp, qwewq, 1234567898, eqw, wqew, 123312, 12312312321aaa12, 123123, uploads/branches/66792af9d3a59. png, , 1231, ewe@ae.com, 25, 1, 2024-06-24 08:14:49, 2024-06-24 08:14:49))

**Comment by yogiofficemail** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
Not Fixed

![Screenshot (340)](https://github.com/antonym8/Tentacle/assets/167422482/d0a90a09-a7b2-4a50-aaa9-208cd5b2bc7d)

**Comment by yogiofficemail** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
Pass
