### ISSUE TITLE
Attendance -> Import showing error

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#48]
![Screenshot (181)](https://github.com/antonym8/Tentacle/assets/142376069/89148cd4-35cd-4b19-9141-58a55a704ef3)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Attendance>Import Showing error - Not Fixed

![Screenshot (162)](https://github.com/antonym8/Tentacle/assets/167423207/0fcf7f45-6360-43b4-8019-4c40932b45dc)

Data Not Found

**Comment by M8Balaji** [comment]
@Nounitha-m8  Working fine
![image](https://github.com/antonym8/Tentacle/assets/150112780/f0ebff3f-40d7-41ef-9c81-546ff7db05c2)

**Comment by Gokilavani-m8** [comment]
Pass
