### ISSUE TITLE
Bonus -> Description in edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#52]
Description is not mandatory field

![Screenshot (185)](https://github.com/antonym8/Tentacle/assets/142376069/2ed43c54-64ca-49c9-8695-d12636f0f2ea)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-04-2024

**Comment by M8Balaji** [comment]
Fixed @Gokilavani-m8 @Nounitha-m8

**Comment by Nounitha-m8** [comment]
@M8Balaji  @yogiofficemail 
1.Need to change the appropriate toast message should be displayed. Finance Categories Added Successfully, need to change it to Bonus Added Successfully, as well as in edit Finance Categories Updated Successfully, need to change it to Bonus Updated Successfully.

![Screenshot (179)](https://github.com/antonym8/Tentacle/assets/167423207/269e57d7-c9cc-4aba-8e98-084e95989f2e)

2.While creating a new bonus with an already existing bonus, a toast message should appear as bonus already exists.

**Comment by M8Balaji** [comment]
@yogiofficemail Check and close - Above issues
https://tssapidemo.m8itsolutions.in/api/updateCategories

https://tssapidemo.m8itsolutions.in/api/addFinanceCategory

**Comment by yogiofficemail** [comment]
fixed

**Comment by Nounitha-m8** [comment]
While creating a new bonus with an already existing bonus, a toast message should appear as bonus already exists - Not Fixed

**Comment by yogiofficemail** [comment]
validation message is sent from the backend need to work in the frontend side

**Comment by M8Balaji** [comment]
@yogiofficemail {
  "name": [
    "The name has already been taken."
  ]
}

Message need as string @yogiofficemail

**Comment by yogiofficemail** [comment]
> @yogiofficemail { "name": [ "The name has already been taken." ] }
> 
> Message need as string @yogiofficemail

{
    "status": 400,
    "message": "The name has already been taken."
} the response is changed as this but still not fixed @M8Balaji

**Comment by M8Balaji** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
Wrong Toast message 

[Recording-20240708_222356.webm](https://github.com/antonym8/Tentacle/assets/167422482/c60ef437-b456-498d-afbd-4c3d460ae802)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
