### ISSUE TITLE
Bonus -> Not able to delete

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#53]
![Screenshot (186)](https://github.com/antonym8/Tentacle/assets/142376069/6e8e59bc-68ad-4487-b9a5-0e35a583d2dc)

**Comment by M8Balaji** [comment]
@yogiofficemail check and fix it

https://tssapidemo.m8itsolutions.in/api/deleteFinaceCategories/134
![image](https://github.com/antonym8/Tentacle/assets/150112780/91989a0b-2b42-4013-a6cc-40b0bbd5b5ab)

**Comment by yogiofficemail** [comment]
> @yogiofficemail check and fix it
> 
> https://tssapidemo.m8itsolutions.in/api/deleteFinaceCategories/134 ![image](https://private-user-images.githubusercontent.com/150112780/335448464-91989a0b-2b42-4013-a6cc-40b0bbd5b5ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzM3OTQsIm5iZiI6MTcxNzEzMzQ5NCwicGF0aCI6Ii8xNTAxMTI3ODAvMzM1NDQ4NDY0LTkxOTg5YTBiLTJiNDItNDAxMy1hNmNjLTQwYjBiYmQ1YjVhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNTMxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWU0MzBkMzVhMjcyYjc0OWNiMGVmMzNkZWVlNTczYTVjYjBjODE1MzBkYmVmYmI5OGEzNDRiNGYzMjY0N2YxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4VOg75Ci7atEiWrRpZ-J_ZeZ_hK-B6MJppJJgJumBB4)

url mistake correct url is https://tssapidemo.m8itsolutions.in/api/deleteFinanceCategories/134

**Comment by M8Balaji** [comment]
FIxed

**Comment by Gokilavani-m8** [comment]
Not fixed

![Screenshot (249)](https://github.com/antonym8/Tentacle/assets/167422482/a85c62db-7ceb-4fd0-a21a-1bd7df700419)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
