### ISSUE TITLE
Loan -> Null value in existing loan details

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#88]
![Screenshot (221)](https://github.com/antonym8/Tentacle/assets/142376069/ebc6e110-f21c-4028-8abc-b66ac035bd4c)

**Comment by M8Balaji** [comment]
@yogiofficemail  https://tssapidemo.m8itsolutions.in/api/checkExistingFinance/150/loan - finance_category_name coming as empty

**Comment by yogiofficemail** [comment]
{
    "id": 24,
    "employee_id": 152,
    "type": "loan",
    "payment_type": "bank",
    "finance_category_id": null,
    "amount": "1000.00",
    "paid_amount": "0.00",
    "due_date": null,
    "remarks": null,
    "duration": 2,
    "interest": "0.00",
    "paid_status": 0,
    "status": 1,
    "approved_by": null,
    "created_by": null,
    "updated_by": null,
    "created_at": "2024-06-30T14:12:25.000000Z",
    "updated_at": "2024-06-30T14:12:25.000000Z",
    "finance_category_name": null,
    "employee_name": null,
    "EmployeeCode": null,
    "fathers_name": null,
    "voucher_no": "VOD-0193",
    "department_name": null,
    "designation_name": null,
    "created_by_name": null
}


while adding a loan for a staff the parameters are sending like this send finance_category_name and finance_category_id from the frontend so it will work

**Comment by yogiofficemail** [comment]
@M8Balaji  check this api https://tssapidemo.m8itsolutions.in/api/addFinanceDetails

> { "id": 24, "employee_id": 152, "type": "loan", "payment_type": "bank", "finance_category_id": null, "amount": "1000.00", "paid_amount": "0.00", "due_date": null, "remarks": null, "duration": 2, "interest": "0.00", "paid_status": 0, "status": 1, "approved_by": null, "created_by": null, "updated_by": null, "created_at": "2024-06-30T14:12:25.000000Z", "updated_at": "2024-06-30T14:12:25.000000Z", "finance_category_name": null, "employee_name": null, "EmployeeCode": null, "fathers_name": null, "voucher_no": "VOD-0193", "department_name": null, "designation_name": null, "created_by_name": null }
> 
> while adding a loan for a staff the parameters are sending like this send finance_category_name and finance_category_id from the frontend so it will work

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Loan -> Null value in existing loan details  - Not fixed
1. Need to set the allignment propely

![image](https://github.com/antonym8/Tentacle/assets/167422482/c90bc546-ea8a-486e-bb93-8d4fa650541e)

**Comment by M8Balaji** [comment]
@yogiofficemail  https://tssapidemo.m8itsolutions.in/api/addFinanceDetails --- payment_type Coming empty

**Comment by yogiofficemail** [comment]
fixed now can add a loan and check

> @yogiofficemail https://tssapidemo.m8itsolutions.in/api/addFinanceDetails --- payment_type Coming empty

**Comment by Gokilavani-m8** [comment]
Not fixed

![image](https://github.com/antonym8/Tentacle/assets/167422482/e3becff1-fe7e-49f9-8e41-40f4bb4f0ffa)

**Comment by M8Balaji** [comment]
Design issue Fixed

**Comment by M8Balaji** [comment]
@yogiofficemail Payment_type is not saving, Please check and fix it

**Comment by yogiofficemail** [comment]
![image](https://github.com/antonym8/Tentacle/assets/112150339/64bfff2b-ccbb-45d1-b274-cee2aa250131)
 after newly adding it will show it in the list

**Comment by Gokilavani-m8** [comment]
Pass
