### ISSUE TITLE
Bonus -> Newly added bonus not showing in the list

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#95]
![Screenshot (228)](https://github.com/antonym8/Tentacle/assets/142376069/80e28a14-1933-4ede-a307-84d8915c8512)

**Comment by M8Balaji** [comment]
@Gokilavani-m8  @Nounitha-m8  Only Come here when it has been approved...!

**Comment by Gokilavani-m8** [comment]
1. Approve>Bonus>Bonus Logs - Failed to approve

![Screenshot (85)](https://github.com/antonym8/Tentacle/assets/167422482/a7c0a327-938a-4502-a32c-4e490c89b884)
 
2. Employee code, Employee name, Department, Designation, Payment type, Type - These fields shouldn't be empty.

**Comment by yogiofficemail** [comment]
https://tsswebdemo.m8itsolutions.in/expense/bonus/add in this page while submitting you are passing id as a employee_id you should get the employee_id from https://tssapidemo.m8itsolutions.in/api/ListEmployeeTentacles?login=2 this api and pass it in the submitting api

**Comment by yogiofficemail** [comment]
list is fixed

**Comment by Gokilavani-m8** [comment]
Bug#1,2 - Not fixed

![Screenshot (268)](https://github.com/antonym8/Tentacle/assets/167422482/dd871cdf-4139-4139-a5d4-526cd177a42d)

**Comment by yogiofficemail** [comment]
approve and reject fixed

**Comment by yogiofficemail** [comment]
> https://tsswebdemo.m8itsolutions.in/expense/bonus/add in this page while submitting you are passing id as a employee_id you should get the employee_id from https://tssapidemo.m8itsolutions.in/api/ListEmployeeTentacles?login=2 this api and pass it in the submitting api

if this is fixed the listing will be fixed

**Comment by M8Balaji** [comment]
![image](https://github.com/antonym8/Tentacle/assets/150112780/4f34c4ff-ed68-47b4-9820-7a4f31bea2e5)
@yogiofficemail Payment type and type data were not coming

https://tssapidemo.m8itsolutions.in/api/bonusApproval

**Comment by Gokilavani-m8** [comment]
While entering employee name as ganesh, it has been shown as ganesh father in the expense list page

![Screenshot (393)](https://github.com/antonym8/Tentacle/assets/167422482/d4a596d0-4fbb-48a5-8da2-1fd8c2e3a511)

**Comment by yogiofficemail** [comment]
![image](https://github.com/antonym8/Tentacle/assets/112150339/412506ef-6ee9-450a-8965-f0ba85345b59)
no payment type and type is in this bonus adding form

**Comment by Gokilavani-m8** [comment]
It is not in adding form. It is in **Approve>Bonus**

**Comment by yogiofficemail** [comment]
No i am saying the payment type and type is not in bonus form

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
